config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :blog_posts

  # Defines the root path route ("/")
  root "blog_posts#index"

  resources :heavy_tasks, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
   primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  scope :sorted, -> { order(published_at: :desc, updated_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
  end

  def show
  end

  def new
    @blog_post = BlogPost.new    
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private
  def blog_post_params
    params.require(:blog_post).permit(:title, :body, :published_at)
  end

  def set_blog_post
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def authenticate_user!
    redirect_to new_user_session_path, alert: "You must sign in or sign up to continue." unless user_signed_in?
  end
end

app/controllers/heavy_tasks_controller.rb
class HeavyTasksController < ApplicationController
  before_action :authenticate_user!

  def create
    HeavyTaskJob.perform_later(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heavy_tasks_helper.rb
module HeavyTasksHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <%= message %><br>
      <% end %>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at, include_blank: true %>
  </div>

  <%= form.button %>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit blog post</h1>

<%= render partial: "form", locals: { blog_post: @blog_post } %>

<%= button_to "Delete", @blog_post,
  method: :delete,
  data: { turbo_confirm: "Are you sure?" }
%>

app/views/blog_posts/index.html.erb
<h1>My Blog</h1>

<%= render partial: "heavy_tasks/button" if user_signed_in? %>

<% @blog_posts.each do |blog_post| %>
  <div>
    <h2><%= link_to blog_post.title, blog_post %></h2>
    <% if blog_post.draft? %>
      <div class="p-2 rounded bg-gray-100 text-gray-900">Draft</div>
    <% elsif blog_post.scheduled? %>
      <div class="p-2 rounded bg-blue-100 text-blue-900">Scheduled</div>
    <% end %>
    <p><%= blog_post.body %></p>
  </div>
<% end %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render partial: "form", locals: { blog_post: @blog_post } %>

app/views/blog_posts/show.html.erb
<%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed_in? %>

<h1 class=""><%= @blog_post.title %></h1>
<%= @blog_post.body %>

app/views/heavy_tasks/_button.html.erb
<%= turbo_stream_from ["heavy_task_channel", current_user] if user_signed_in? %>

<div id="heavy_task">
  <%= button_to "Perform Heavy Task", heavy_tasks_path, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
</div>

app/views/heavy_tasks/_progress.html.erb
<div id="heavy_task" data-controller="progress-bar" data-progress-bar-total-jobs-value="<%= total_count %>">
  <div class="w-full h-6 bg-gray-200 rounded-full dark:bg-gray-700">
    <div class="h-6 bg-blue-600 rounded-full dark:bg-blue-500"
      role="progressbar"
      data-progress-bar-target="progress"
    ></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  <div>
    <% if user_signed_in? %>
      <%= link_to "List blog post", root_path %>
      <%= link_to "New blog post", new_blog_post_path %>
      <%= link_to "Profile", edit_user_registration_path %>
      <%= button_to "Log out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
  </div>

    <%= yield %>
  </body>
</html>